#!/usr/bin/env bash

export JAVA_OPTS="\
       -Djdk.tracePinnedThreads=short \
       -XX:+EnableDynamicAgentLoading \
       -XX:-OmitStackTraceInFastThrow \
       -XX:+UnlockDiagnosticVMOptions \
       -XX:+DebugNonSafepoints \
       --sun-misc-unsafe-memory-access=allow \
       --enable-native-access=ALL-UNNAMED \
       --enable-preview";

set -ex

clojure -M:dev -m rebel-readline.main
